version: "3.7"
   
services:
  db:
    image: postgres:12.11-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=effortles
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  web:
    build: .
    volumes:
      - .:/code
    entrypoint: ./startup_script.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=effortles
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - db
  redis:
    image: redis:7.0.2-alpine
    ports:
      - "6379:6379"
  celery_worker:
    restart: always
    build:
      context: .
    command: celery -A effortles worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - web
      