# Generated by Django 4.0.4 on 2022-05-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('loss_of_pay_leave', 'Loss Of Pay Leave'), ('paid_leave', 'Paid Leave'), ('half_day_leave', 'Half Day Leave')], max_length=20)),
                ('swipe_status', models.CharField(choices=[('swiped_in', 'Swiped In'), ('swiped_out', 'Swiped Out')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Swipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_swipe', models.TimeField(auto_now_add=True)),
                ('swipe_status', models.CharField(choices=[('swiped_in', 'Swiped In'), ('swiped_out', 'Swiped Out')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.attendance')),
            ],
        ),
    ]
