# Generated by Django 4.0 on 2022-06-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='swipe_status',
            field=models.CharField(choices=[('swiped_in', 'Swiped In'), ('swiped_out', 'Swiped Out'), ('absent', 'Absent')], max_length=10),
        ),
    ]
