# Generated by Django 4.0 on 2022-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='transaction_status',
            field=models.CharField(choices=[('Not Confirmed', 'not_confirmed'), ('Confirmed', 'confirmed')], default='not_confirmed', max_length=16),
        ),
    ]
