# Generated by Django 4.0 on 2022-06-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='post_and_comment_field_mutually_exclusive',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('post', None), models.Q(('comment', None), _negated=True)), models.Q(models.Q(('post', None), _negated=True), ('comment', None)), _connector='OR')), name='post_and_comment_field_mutually_exclusive'),
        ),
    ]
