# Generated by Django 4.0 on 2022-06-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_user_permissions'),
        ('feed', '0002_remove_like_post_and_comment_field_mutually_exclusive_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('comment', 'user'), ('post', 'user')},
        ),
    ]
