# Generated by Django 4.0 on 2022-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
